repo: 'more-than-just-datum'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - css-order-modules-grid-type-main
  - modulifier
  - modulifier-list-group
  - gridifier
  - typografier
  - forms
  - google-fonts
  - screenshots-all

html:
  - path: 'index.html'
    has:
      - 'table > thead > tr > th[scope]'
      - 'table > tbody > tr > th[scope]'
      - 'tbody > tr:nth-child(25)'
      - 'tr > td:nth-child(8)'
    search:
      - 'Playground Finder'
      - 'Search'
      - 'Nearest playgrounds'
      - 'Playgrounds in the city'
      - '373'
      - 'Distance'
      - '0.75 km'
      - '1700'
      - '2.58 km'
      - '960'
      - '3.03 km'
      - 'Park ID'
      - 'Park type'
      - 'Age group'
      - 'Swings'
      - 'Slides'
      - 'Seesaws'
      - 'Sandboxes'
      - 'Playhouses'
      - 'Play structure'
      - 'Junior'
      - 'Play area'
      - 'Junior'
      - 'Yes'
      - 'No'

css:
  - path: 'css/main.css'
    has:
      - ['html', 'font-family', '"IBM Plex Sans", sans-serif']
    search:
      - '200px'
      - '#efefef'
      - '#fff'
      - '#ddd'
